using System.Collections.Concurrent;

namespace LanWatcher.Services;

public interface IOuiLookupService
{
    string GetManufacturer(string macAddress);
    string GetAdapterType(string macAddress);
}

/// <summary>
/// Service to look up manufacturer information from MAC address OUI (Organizationally Unique Identifier)
/// The first 3 bytes of a MAC address identify the manufacturer
/// </summary>
public class OuiLookupService : IOuiLookupService
{
    private static readonly Dictionary<string, (string Manufacturer, string Type)> OuiDatabase = new(StringComparer.OrdinalIgnoreCase)
    {
        // Apple
        { "00:03:93", ("Apple", "WiFi") },
        { "00:0A:95", ("Apple", "WiFi") },
        { "00:0D:93", ("Apple", "WiFi") },
        { "00:1C:B3", ("Apple", "WiFi") },
        { "00:1F:F3", ("Apple", "WiFi") },
        { "00:21:E9", ("Apple", "WiFi") },
        { "00:23:12", ("Apple", "WiFi") },
        { "00:25:00", ("Apple", "WiFi") },
        { "00:26:08", ("Apple", "WiFi") },
        { "00:26:B0", ("Apple", "WiFi") },
        { "00:26:BB", ("Apple", "WiFi") },
        { "10:DD:B1", ("Apple", "WiFi") },
        { "14:10:9F", ("Apple", "WiFi") },
        { "18:E7:F4", ("Apple", "WiFi") },
        { "28:E0:2C", ("Apple", "WiFi") },
        { "34:36:3B", ("Apple", "WiFi") },
        { "38:C9:86", ("Apple", "WiFi") },
        { "3C:07:54", ("Apple", "WiFi") },
        { "40:6C:8F", ("Apple", "WiFi") },
        { "44:2A:60", ("Apple", "WiFi") },
        { "48:D7:05", ("Apple", "WiFi") },
        { "58:55:CA", ("Apple", "WiFi") },
        { "60:03:08", ("Apple", "WiFi") },
        { "64:20:0C", ("Apple", "WiFi") },
        { "68:64:4B", ("Apple", "WiFi") },
        { "7C:D1:C3", ("Apple", "WiFi") },
        { "80:E6:50", ("Apple", "WiFi") },
        { "84:38:35", ("Apple", "WiFi") },
        { "88:66:A5", ("Apple", "WiFi") },
        { "8C:85:90", ("Apple", "WiFi") },
        { "90:8D:6C", ("Apple", "WiFi") },
        { "98:01:A7", ("Apple", "WiFi") },
        { "98:D6:BB", ("Apple", "WiFi") },
        { "A4:5E:60", ("Apple", "WiFi") },
        { "A8:66:7F", ("Apple", "WiFi") },
        { "AC:BC:32", ("Apple", "WiFi") },
        { "B0:34:95", ("Apple", "WiFi") },
        { "B4:18:D1", ("Apple", "WiFi") },
        { "B8:09:8A", ("Apple", "WiFi") },
        { "B8:17:C2", ("Apple", "WiFi") },
        { "BC:3B:AF", ("Apple", "WiFi") },
        { "C0:CE:CD", ("Apple", "WiFi") },
        { "C8:85:50", ("Apple", "WiFi") },
        { "CC:08:E0", ("Apple", "WiFi") },
        { "D0:25:98", ("Apple", "WiFi") },
        { "D4:F4:6F", ("Apple", "WiFi") },
        { "DC:2B:2A", ("Apple", "WiFi") },
        { "E0:C7:67", ("Apple", "WiFi") },
        { "E4:25:E7", ("Apple", "WiFi") },
        { "F0:B4:79", ("Apple", "WiFi") },
        { "F4:5C:89", ("Apple", "WiFi") },
        
        // Samsung
        { "00:07:AB", ("Samsung", "WiFi") },
        { "00:12:47", ("Samsung", "WiFi") },
        { "00:12:FB", ("Samsung", "WiFi") },
        { "00:13:77", ("Samsung", "WiFi") },
        { "00:15:99", ("Samsung", "WiFi") },
        { "00:16:32", ("Samsung", "WiFi") },
        { "00:17:D5", ("Samsung", "WiFi") },
        { "00:18:AF", ("Samsung", "WiFi") },
        { "00:1A:8A", ("Samsung", "WiFi") },
        { "00:1B:98", ("Samsung", "WiFi") },
        { "00:1D:25", ("Samsung", "WiFi") },
        { "00:1E:7D", ("Samsung", "WiFi") },
        { "00:21:19", ("Samsung", "WiFi") },
        { "00:24:54", ("Samsung", "WiFi") },
        { "00:26:37", ("Samsung", "WiFi") },
        { "14:49:E0", ("Samsung", "WiFi") },
        { "18:3A:2D", ("Samsung", "WiFi") },
        { "1C:62:B8", ("Samsung", "WiFi") },
        { "24:4B:81", ("Samsung", "WiFi") },
        { "28:98:7B", ("Samsung", "WiFi") },
        { "34:23:BA", ("Samsung", "WiFi") },
        { "38:01:95", ("Samsung", "WiFi") },
        { "40:0E:85", ("Samsung", "WiFi") },
        { "50:01:BB", ("Samsung", "WiFi") },
        { "50:B7:C3", ("Samsung", "WiFi") },
        { "54:40:AD", ("Samsung", "WiFi") },
        { "5C:0A:5B", ("Samsung", "WiFi") },
        { "64:B3:10", ("Samsung", "WiFi") },
        { "78:D6:F0", ("Samsung", "WiFi") },
        { "84:25:DB", ("Samsung", "WiFi") },
        { "90:18:7C", ("Samsung", "WiFi") },
        { "94:35:0A", ("Samsung", "WiFi") },
        { "A0:82:1F", ("Samsung", "WiFi") },
        { "AC:5F:3E", ("Samsung", "WiFi") },
        { "B4:3A:28", ("Samsung", "WiFi") },
        { "BC:44:86", ("Samsung", "WiFi") },
        { "C4:57:6E", ("Samsung", "WiFi") },
        { "D0:22:BE", ("Samsung", "WiFi") },
        { "D8:90:E8", ("Samsung", "WiFi") },
        { "E4:7C:F9", ("Samsung", "WiFi") },
        { "E8:50:8B", ("Samsung", "WiFi") },
        { "F0:25:B7", ("Samsung", "WiFi") },
        { "F4:7B:5E", ("Samsung", "WiFi") },

        // Google/Nest
        { "00:1A:11", ("Google", "WiFi") },
        { "1C:F2:9A", ("Google", "WiFi") },
        { "20:DF:B9", ("Google", "WiFi") },
        { "54:60:09", ("Google", "WiFi") },
        { "94:EB:2C", ("Google", "WiFi") },
        { "F4:F5:D8", ("Google", "WiFi") },
        { "F4:F5:E8", ("Google", "WiFi") },
        { "18:D6:C7", ("Google/Nest", "WiFi") },
        { "64:16:66", ("Google/Nest", "WiFi") },

        // Microsoft
        { "00:0D:3A", ("Microsoft", "Ethernet") },
        { "00:12:5A", ("Microsoft", "Ethernet") },
        { "00:15:5D", ("Microsoft/Hyper-V", "Virtual") },
        { "00:17:FA", ("Microsoft", "Ethernet") },
        { "00:1D:D8", ("Microsoft", "Ethernet") },
        { "00:22:48", ("Microsoft", "Ethernet") },
        { "00:25:AE", ("Microsoft", "Ethernet") },
        { "28:18:78", ("Microsoft", "WiFi") },
        { "30:59:B7", ("Microsoft", "WiFi") },
        { "50:1A:C5", ("Microsoft", "WiFi") },
        { "58:82:A8", ("Microsoft", "WiFi") },
        { "60:45:BD", ("Microsoft", "WiFi") },
        { "7C:1E:52", ("Microsoft", "WiFi") },
        { "98:5F:D3", ("Microsoft", "WiFi") },
        { "B4:0E:DE", ("Microsoft", "WiFi") },
        { "C8:3D:D4", ("Microsoft", "WiFi") },
        { "D8:9E:F3", ("Microsoft", "WiFi") },
        { "DC:53:60", ("Microsoft", "Ethernet") },

        // Intel
        { "00:02:B3", ("Intel", "Ethernet") },
        { "00:03:47", ("Intel", "Ethernet") },
        { "00:04:23", ("Intel", "Ethernet") },
        { "00:07:E9", ("Intel", "Ethernet") },
        { "00:0C:F1", ("Intel", "Ethernet") },
        { "00:0E:0C", ("Intel", "Ethernet") },
        { "00:0E:35", ("Intel", "Ethernet") },
        { "00:11:11", ("Intel", "Ethernet") },
        { "00:12:F0", ("Intel", "Ethernet") },
        { "00:13:02", ("Intel", "Ethernet") },
        { "00:13:20", ("Intel", "Ethernet") },
        { "00:13:CE", ("Intel", "Ethernet") },
        { "00:13:E8", ("Intel", "Ethernet") },
        { "00:15:00", ("Intel", "Ethernet") },
        { "00:15:17", ("Intel", "WiFi") },
        { "00:16:6F", ("Intel", "Ethernet") },
        { "00:16:76", ("Intel", "WiFi") },
        { "00:16:EA", ("Intel", "Ethernet") },
        { "00:16:EB", ("Intel", "Ethernet") },
        { "00:18:DE", ("Intel", "WiFi") },
        { "00:19:D1", ("Intel", "WiFi") },
        { "00:19:D2", ("Intel", "Ethernet") },
        { "00:1B:21", ("Intel", "Ethernet") },
        { "00:1B:77", ("Intel", "WiFi") },
        { "00:1C:BF", ("Intel", "WiFi") },
        { "00:1D:E0", ("Intel", "WiFi") },
        { "00:1E:64", ("Intel", "WiFi") },
        { "00:1E:65", ("Intel", "Ethernet") },
        { "00:1F:3B", ("Intel", "Ethernet") },
        { "00:1F:3C", ("Intel", "WiFi") },
        { "00:20:E0", ("Intel", "Ethernet") },
        { "00:21:5C", ("Intel", "WiFi") },
        { "00:21:5D", ("Intel", "Ethernet") },
        { "00:21:6A", ("Intel", "Ethernet") },
        { "00:21:6B", ("Intel", "WiFi") },
        { "00:22:FA", ("Intel", "WiFi") },
        { "00:22:FB", ("Intel", "Ethernet") },
        { "00:24:D6", ("Intel", "Ethernet") },
        { "00:24:D7", ("Intel", "WiFi") },
        { "00:26:C6", ("Intel", "Ethernet") },
        { "00:26:C7", ("Intel", "WiFi") },
        { "00:27:10", ("Intel", "Ethernet") },
        { "24:77:03", ("Intel", "WiFi") },
        { "3C:A9:F4", ("Intel", "WiFi") },
        { "48:51:B7", ("Intel", "WiFi") },
        { "4C:EB:42", ("Intel", "WiFi") },
        { "5C:51:4F", ("Intel", "WiFi") },
        { "5C:E0:C5", ("Intel", "WiFi") },
        { "68:05:CA", ("Intel", "Ethernet") },
        { "6C:88:14", ("Intel", "WiFi") },
        { "80:19:34", ("Intel", "WiFi") },
        { "8C:EC:4B", ("Intel", "WiFi") },
        { "98:4F:EE", ("Intel", "Ethernet") },
        { "9C:DA:3E", ("Intel", "WiFi") },
        { "A4:02:B9", ("Intel", "WiFi") },
        { "A4:34:D9", ("Intel", "WiFi") },
        { "AC:7B:A1", ("Intel", "WiFi") },
        { "B4:6B:FC", ("Intel", "WiFi") },
        { "B8:08:CF", ("Intel", "WiFi") },
        { "C8:FF:28", ("Intel", "WiFi") },
        { "D4:3D:7E", ("Intel", "WiFi") },
        { "DC:1B:A1", ("Intel", "WiFi") },
        { "E8:B1:FC", ("Intel", "WiFi") },
        { "EC:0E:C4", ("Intel", "WiFi") },
        { "F4:06:69", ("Intel", "WiFi") },

        // Cisco/Linksys
        { "00:00:0C", ("Cisco", "Ethernet") },
        { "00:01:42", ("Cisco", "Ethernet") },
        { "00:01:43", ("Cisco", "Ethernet") },
        { "00:01:63", ("Cisco", "Ethernet") },
        { "00:01:64", ("Cisco", "Ethernet") },
        { "00:01:96", ("Cisco", "Ethernet") },
        { "00:01:97", ("Cisco", "Ethernet") },
        { "00:01:C7", ("Cisco", "Ethernet") },
        { "00:01:C9", ("Cisco", "Ethernet") },
        { "00:02:16", ("Cisco", "Ethernet") },
        { "00:02:17", ("Cisco", "Ethernet") },
        { "00:02:3D", ("Cisco", "Ethernet") },
        { "00:02:4A", ("Cisco", "Ethernet") },
        { "00:02:4B", ("Cisco", "Ethernet") },
        { "00:02:7D", ("Cisco", "Ethernet") },
        { "00:02:7E", ("Cisco", "Ethernet") },
        { "00:02:B9", ("Cisco", "Ethernet") },
        { "00:02:BA", ("Cisco", "Ethernet") },
        { "00:02:FC", ("Cisco", "Ethernet") },
        { "00:02:FD", ("Cisco", "Ethernet") },
        { "00:06:7C", ("Cisco", "Ethernet") },
        { "00:06:C1", ("Cisco", "Ethernet") },
        { "00:06:D6", ("Cisco", "Ethernet") },
        { "00:06:D7", ("Cisco", "Ethernet") },
        { "00:06:F6", ("Cisco", "Ethernet") },
        { "00:0A:41", ("Cisco", "Ethernet") },
        { "00:0A:42", ("Cisco", "Ethernet") },
        { "00:0A:8A", ("Cisco", "Ethernet") },
        { "00:0A:B7", ("Cisco", "Ethernet") },
        { "00:0A:B8", ("Cisco", "Ethernet") },
        { "00:0B:45", ("Cisco", "Ethernet") },
        { "00:0B:46", ("Cisco", "Ethernet") },
        { "00:0B:5F", ("Cisco", "Ethernet") },
        { "00:0B:60", ("Cisco", "Ethernet") },
        { "00:0B:85", ("Cisco", "Ethernet") },
        { "00:0B:BE", ("Cisco", "Ethernet") },
        { "00:0B:BF", ("Cisco", "Ethernet") },
        { "00:0C:30", ("Cisco", "Ethernet") },
        { "00:0C:31", ("Cisco", "Ethernet") },
        { "00:0C:85", ("Cisco", "Ethernet") },
        { "00:0D:28", ("Cisco", "Ethernet") },
        { "00:0D:29", ("Cisco", "Ethernet") },
        { "00:0D:65", ("Cisco", "Ethernet") },
        { "00:0D:66", ("Cisco", "Ethernet") },
        { "00:0E:08", ("Cisco", "Ethernet") },
        { "00:0E:38", ("Cisco", "Ethernet") },
        { "00:0E:39", ("Cisco", "Ethernet") },
        { "00:0E:83", ("Cisco", "Ethernet") },
        { "00:0E:84", ("Cisco", "Ethernet") },
        { "00:0E:D6", ("Cisco", "Ethernet") },
        { "00:0E:D7", ("Cisco", "Ethernet") },
        { "00:0F:23", ("Cisco", "Ethernet") },
        { "00:0F:24", ("Cisco", "Ethernet") },
        { "00:0F:34", ("Cisco/Linksys", "WiFi") },
        { "00:0F:66", ("Cisco/Linksys", "WiFi") },
        { "00:12:17", ("Cisco/Linksys", "WiFi") },
        { "00:14:BF", ("Cisco/Linksys", "WiFi") },
        { "00:16:B6", ("Cisco/Linksys", "WiFi") },
        { "00:18:39", ("Cisco/Linksys", "WiFi") },
        { "00:18:F8", ("Cisco/Linksys", "WiFi") },
        { "00:1A:70", ("Cisco/Linksys", "WiFi") },
        { "00:1C:10", ("Cisco/Linksys", "WiFi") },
        { "00:1D:7E", ("Cisco/Linksys", "WiFi") },
        { "00:1E:E5", ("Cisco/Linksys", "WiFi") },
        { "00:21:29", ("Cisco/Linksys", "WiFi") },
        { "00:22:6B", ("Cisco/Linksys", "WiFi") },
        { "00:23:69", ("Cisco/Linksys", "WiFi") },
        { "00:25:9C", ("Cisco/Linksys", "WiFi") },

        // TP-Link
        { "00:1D:0F", ("TP-Link", "WiFi") },
        { "00:27:19", ("TP-Link", "WiFi") },
        { "10:FE:ED", ("TP-Link", "WiFi") },
        { "14:CC:20", ("TP-Link", "WiFi") },
        { "14:CF:92", ("TP-Link", "WiFi") },
        { "18:A6:F7", ("TP-Link", "WiFi") },
        { "1C:3B:F3", ("TP-Link", "WiFi") },
        { "24:69:68", ("TP-Link", "WiFi") },
        { "30:B5:C2", ("TP-Link", "WiFi") },
        { "50:C7:BF", ("TP-Link", "WiFi") },
        { "54:C8:0F", ("TP-Link", "WiFi") },
        { "60:E3:27", ("TP-Link", "WiFi") },
        { "64:70:02", ("TP-Link", "WiFi") },
        { "6C:5A:B0", ("TP-Link", "WiFi") },
        { "70:4F:57", ("TP-Link", "WiFi") },
        { "74:DA:38", ("TP-Link", "WiFi") },
        { "78:44:76", ("TP-Link", "WiFi") },
        { "7C:8B:CA", ("TP-Link", "WiFi") },
        { "80:89:17", ("TP-Link", "WiFi") },
        { "84:16:F9", ("TP-Link", "WiFi") },
        { "88:1F:A1", ("TP-Link", "WiFi") },
        { "90:F6:52", ("TP-Link", "WiFi") },
        { "94:0C:6D", ("TP-Link", "WiFi") },
        { "98:DA:C4", ("TP-Link", "WiFi") },
        { "A0:F3:C1", ("TP-Link", "WiFi") },
        { "AC:84:C6", ("TP-Link", "WiFi") },
        { "B0:4E:26", ("TP-Link", "WiFi") },
        { "B0:95:75", ("TP-Link", "WiFi") },
        { "B4:B0:24", ("TP-Link", "WiFi") },
        { "C0:25:E9", ("TP-Link", "WiFi") },
        { "C4:E9:84", ("TP-Link", "WiFi") },
        { "CC:32:E5", ("TP-Link", "WiFi") },
        { "D4:6E:0E", ("TP-Link", "WiFi") },
        { "D8:07:B6", ("TP-Link", "WiFi") },
        { "DC:FE:18", ("TP-Link", "WiFi") },
        { "E4:D3:32", ("TP-Link", "WiFi") },
        { "EC:08:6B", ("TP-Link", "WiFi") },
        { "EC:17:2F", ("TP-Link", "WiFi") },
        { "F4:EC:38", ("TP-Link", "WiFi") },
        { "F8:1A:67", ("TP-Link", "WiFi") },

        // Netgear
        { "00:09:5B", ("Netgear", "WiFi") },
        { "00:0F:B5", ("Netgear", "WiFi") },
        { "00:14:6C", ("Netgear", "WiFi") },
        { "00:18:4D", ("Netgear", "WiFi") },
        { "00:1B:2F", ("Netgear", "WiFi") },
        { "00:1E:2A", ("Netgear", "WiFi") },
        { "00:1F:33", ("Netgear", "WiFi") },
        { "00:22:3F", ("Netgear", "WiFi") },
        { "00:24:B2", ("Netgear", "WiFi") },
        { "00:26:F2", ("Netgear", "WiFi") },
        { "04:A1:51", ("Netgear", "WiFi") },
        { "08:BD:43", ("Netgear", "WiFi") },
        { "10:0D:7F", ("Netgear", "WiFi") },
        { "10:DA:43", ("Netgear", "WiFi") },
        { "20:0C:C8", ("Netgear", "WiFi") },
        { "20:4E:7F", ("Netgear", "WiFi") },
        { "28:C6:8E", ("Netgear", "WiFi") },
        { "2C:B0:5D", ("Netgear", "WiFi") },
        { "30:46:9A", ("Netgear", "WiFi") },
        { "44:94:FC", ("Netgear", "WiFi") },
        { "4C:60:DE", ("Netgear", "WiFi") },
        { "6C:B0:CE", ("Netgear", "WiFi") },
        { "84:1B:5E", ("Netgear", "WiFi") },
        { "9C:3D:CF", ("Netgear", "WiFi") },
        { "A0:04:60", ("Netgear", "WiFi") },
        { "A4:2B:8C", ("Netgear", "WiFi") },
        { "B0:7F:B9", ("Netgear", "WiFi") },
        { "C0:3F:0E", ("Netgear", "WiFi") },
        { "C4:04:15", ("Netgear", "WiFi") },
        { "C4:3D:C7", ("Netgear", "WiFi") },
        { "DC:EF:09", ("Netgear", "WiFi") },
        { "E0:46:9A", ("Netgear", "WiFi") },
        { "E0:91:F5", ("Netgear", "WiFi") },
        { "E4:F4:C6", ("Netgear", "WiFi") },
        { "F8:73:94", ("Netgear", "WiFi") },

        // ASUS
        { "00:0C:6E", ("ASUS", "Ethernet") },
        { "00:0E:A6", ("ASUS", "Ethernet") },
        { "00:11:2F", ("ASUS", "Ethernet") },
        { "00:11:D8", ("ASUS", "Ethernet") },
        { "00:13:D4", ("ASUS", "Ethernet") },
        { "00:15:F2", ("ASUS", "Ethernet") },
        { "00:17:31", ("ASUS", "Ethernet") },
        { "00:18:F3", ("ASUS", "Ethernet") },
        { "00:1A:92", ("ASUS", "Ethernet") },
        { "00:1D:60", ("ASUS", "Ethernet") },
        { "00:1E:8C", ("ASUS", "Ethernet") },
        { "00:1F:C6", ("ASUS", "Ethernet") },
        { "00:22:15", ("ASUS", "Ethernet") },
        { "00:23:54", ("ASUS", "Ethernet") },
        { "00:24:8C", ("ASUS", "Ethernet") },
        { "00:26:18", ("ASUS", "Ethernet") },
        { "04:92:26", ("ASUS", "WiFi") },
        { "04:D4:C4", ("ASUS", "WiFi") },
        { "08:60:6E", ("ASUS", "WiFi") },
        { "10:7B:44", ("ASUS", "WiFi") },
        { "10:BF:48", ("ASUS", "WiFi") },
        { "10:C3:7B", ("ASUS", "WiFi") },
        { "14:DA:E9", ("ASUS", "WiFi") },
        { "1C:87:2C", ("ASUS", "WiFi") },
        { "20:CF:30", ("ASUS", "WiFi") },
        { "2C:4D:54", ("ASUS", "WiFi") },
        { "2C:56:DC", ("ASUS", "WiFi") },
        { "30:5A:3A", ("ASUS", "WiFi") },
        { "30:85:A9", ("ASUS", "WiFi") },
        { "34:97:F6", ("ASUS", "WiFi") },
        { "38:2C:4A", ("ASUS", "WiFi") },
        { "3C:7C:3F", ("ASUS", "WiFi") },
        { "40:16:7E", ("ASUS", "WiFi") },
        { "4C:ED:FB", ("ASUS", "WiFi") },
        { "50:46:5D", ("ASUS", "WiFi") },
        { "54:04:A6", ("ASUS", "WiFi") },
        { "60:45:CB", ("ASUS", "WiFi") },
        { "74:D0:2B", ("ASUS", "WiFi") },
        { "AC:9E:17", ("ASUS", "WiFi") },
        { "B0:6E:BF", ("ASUS", "WiFi") },
        { "BC:EE:7B", ("ASUS", "WiFi") },
        { "C8:60:00", ("ASUS", "WiFi") },
        { "D8:50:E6", ("ASUS", "WiFi") },
        { "E0:3F:49", ("ASUS", "WiFi") },
        { "F4:6D:04", ("ASUS", "WiFi") },

        // Dell
        { "00:06:5B", ("Dell", "Ethernet") },
        { "00:08:74", ("Dell", "Ethernet") },
        { "00:0B:DB", ("Dell", "Ethernet") },
        { "00:0D:56", ("Dell", "Ethernet") },
        { "00:0F:1F", ("Dell", "Ethernet") },
        { "00:11:43", ("Dell", "Ethernet") },
        { "00:12:3F", ("Dell", "Ethernet") },
        { "00:13:72", ("Dell", "Ethernet") },
        { "00:14:22", ("Dell", "Ethernet") },
        { "00:15:C5", ("Dell", "Ethernet") },
        { "00:16:F0", ("Dell", "Ethernet") },
        { "00:18:8B", ("Dell", "Ethernet") },
        { "00:19:B9", ("Dell", "Ethernet") },
        { "00:1A:A0", ("Dell", "Ethernet") },
        { "00:1C:23", ("Dell", "Ethernet") },
        { "00:1D:09", ("Dell", "Ethernet") },
        { "00:1E:4F", ("Dell", "Ethernet") },
        { "00:1E:C9", ("Dell", "Ethernet") },
        { "00:21:70", ("Dell", "Ethernet") },
        { "00:21:9B", ("Dell", "Ethernet") },
        { "00:22:19", ("Dell", "Ethernet") },
        { "00:23:AE", ("Dell", "Ethernet") },
        { "00:24:E8", ("Dell", "Ethernet") },
        { "00:25:64", ("Dell", "Ethernet") },
        { "00:26:B9", ("Dell", "Ethernet") },
        { "14:18:77", ("Dell", "Ethernet") },
        { "14:B3:1F", ("Dell", "Ethernet") },
        { "14:FE:B5", ("Dell", "Ethernet") },
        { "18:03:73", ("Dell", "Ethernet") },
        { "18:66:DA", ("Dell", "Ethernet") },
        { "18:A9:9B", ("Dell", "Ethernet") },
        { "18:DB:F2", ("Dell", "Ethernet") },
        { "24:6E:96", ("Dell", "Ethernet") },
        { "24:B6:FD", ("Dell", "Ethernet") },
        { "28:F1:0E", ("Dell", "Ethernet") },
        { "34:17:EB", ("Dell", "Ethernet") },
        { "34:E6:D7", ("Dell", "Ethernet") },
        { "44:A8:42", ("Dell", "Ethernet") },
        { "4C:76:25", ("Dell", "Ethernet") },
        { "54:9F:35", ("Dell", "Ethernet") },
        { "5C:26:0A", ("Dell", "Ethernet") },
        { "5C:F9:DD", ("Dell", "Ethernet") },
        { "64:00:6A", ("Dell", "Ethernet") },
        { "78:2B:CB", ("Dell", "Ethernet") },
        { "84:7B:EB", ("Dell", "Ethernet") },
        { "98:90:96", ("Dell", "Ethernet") },
        { "B0:83:FE", ("Dell", "Ethernet") },
        { "B4:E1:0F", ("Dell", "Ethernet") },
        { "BC:30:5B", ("Dell", "Ethernet") },
        { "D4:81:D7", ("Dell", "Ethernet") },
        { "E4:54:E8", ("Dell", "Ethernet") },
        { "F0:1F:AF", ("Dell", "Ethernet") },
        { "F8:B1:56", ("Dell", "Ethernet") },
        { "F8:BC:12", ("Dell", "Ethernet") },
        { "F8:CA:B8", ("Dell", "Ethernet") },
        { "F8:DB:88", ("Dell", "Ethernet") },

        // HP
        { "00:01:E6", ("HP", "Ethernet") },
        { "00:01:E7", ("HP", "Ethernet") },
        { "00:02:A5", ("HP", "Ethernet") },
        { "00:04:EA", ("HP", "Ethernet") },
        { "00:08:02", ("HP", "Ethernet") },
        { "00:08:83", ("HP", "Ethernet") },
        { "00:0A:57", ("HP", "Ethernet") },
        { "00:0B:CD", ("HP", "Ethernet") },
        { "00:0D:9D", ("HP", "Ethernet") },
        { "00:0E:7F", ("HP", "Ethernet") },
        { "00:0F:20", ("HP", "Ethernet") },
        { "00:0F:61", ("HP", "Ethernet") },
        { "00:10:83", ("HP", "Ethernet") },
        { "00:10:E3", ("HP", "Ethernet") },
        { "00:11:0A", ("HP", "Ethernet") },
        { "00:11:85", ("HP", "Ethernet") },
        { "00:12:79", ("HP", "Ethernet") },
        { "00:13:21", ("HP", "Ethernet") },
        { "00:14:38", ("HP", "Ethernet") },
        { "00:14:C2", ("HP", "Ethernet") },
        { "00:15:60", ("HP", "Ethernet") },
        { "00:16:35", ("HP", "Ethernet") },
        { "00:17:08", ("HP", "Ethernet") },
        { "00:17:A4", ("HP", "Ethernet") },
        { "00:18:FE", ("HP", "Ethernet") },
        { "00:19:BB", ("HP", "Ethernet") },
        { "00:1A:4B", ("HP", "Ethernet") },
        { "00:1B:78", ("HP", "Ethernet") },
        { "00:1C:C4", ("HP", "Ethernet") },
        { "00:1E:0B", ("HP", "Ethernet") },
        { "00:1F:29", ("HP", "Ethernet") },
        { "00:21:5A", ("HP", "Ethernet") },
        { "00:22:64", ("HP", "Ethernet") },
        { "00:23:7D", ("HP", "Ethernet") },
        { "00:24:81", ("HP", "Ethernet") },
        { "00:25:B3", ("HP", "Ethernet") },
        { "00:26:55", ("HP", "Ethernet") },
        { "08:00:09", ("HP", "Ethernet") },
        { "10:00:90", ("HP", "Ethernet") },
        { "10:1F:74", ("HP", "Ethernet") },
        { "10:60:4B", ("HP", "Ethernet") },
        { "14:02:EC", ("HP", "Ethernet") },
        { "14:58:D0", ("HP", "Ethernet") },
        { "18:A9:05", ("HP", "Ethernet") },
        { "1C:C1:DE", ("HP", "Ethernet") },
        { "24:BE:05", ("HP", "Ethernet") },
        { "28:80:23", ("HP", "Ethernet") },
        { "28:92:4A", ("HP", "Ethernet") },
        { "2C:27:D7", ("HP", "Ethernet") },
        { "2C:41:38", ("HP", "Ethernet") },
        { "2C:44:FD", ("HP", "Ethernet") },
        { "2C:59:E5", ("HP", "Ethernet") },
        { "30:E1:71", ("HP", "Ethernet") },
        { "34:64:A9", ("HP", "Ethernet") },
        { "38:63:BB", ("HP", "Ethernet") },
        { "3C:4A:92", ("HP", "Ethernet") },
        { "3C:D9:2B", ("HP", "Ethernet") },
        { "40:A8:F0", ("HP", "Ethernet") },
        { "44:1E:A1", ("HP", "Ethernet") },
        { "48:0F:CF", ("HP", "Ethernet") },
        { "48:DF:37", ("HP", "Ethernet") },
        { "4C:39:09", ("HP", "Ethernet") },
        { "50:65:F3", ("HP", "Ethernet") },
        { "58:20:B1", ("HP", "Ethernet") },
        { "5C:B9:01", ("HP", "Ethernet") },
        { "64:51:06", ("HP", "Ethernet") },
        { "68:B5:99", ("HP", "Ethernet") },
        { "6C:3B:E5", ("HP", "Ethernet") },
        { "70:10:6F", ("HP", "Ethernet") },
        { "74:46:A0", ("HP", "Ethernet") },
        { "78:48:59", ("HP", "Ethernet") },
        { "78:AC:C0", ("HP", "Ethernet") },
        { "80:C1:6E", ("HP", "Ethernet") },
        { "84:34:97", ("HP", "Ethernet") },
        { "88:51:FB", ("HP", "Ethernet") },
        { "8C:DC:D4", ("HP", "Ethernet") },
        { "94:18:82", ("HP", "Ethernet") },
        { "94:57:A5", ("HP", "Ethernet") },
        { "98:4B:E1", ("HP", "Ethernet") },
        { "98:E7:F4", ("HP", "Ethernet") },
        { "9C:8E:99", ("HP", "Ethernet") },
        { "9C:B6:54", ("HP", "Ethernet") },
        { "A0:1D:48", ("HP", "Ethernet") },
        { "A0:2B:B8", ("HP", "Ethernet") },
        { "A0:D3:C1", ("HP", "Ethernet") },
        { "A4:5D:36", ("HP", "Ethernet") },
        { "B0:5A:DA", ("HP", "Ethernet") },
        { "B4:99:BA", ("HP", "Ethernet") },
        { "B4:B5:2F", ("HP", "Ethernet") },
        { "B8:AF:67", ("HP", "Ethernet") },
        { "C0:91:34", ("HP", "Ethernet") },
        { "C4:34:6B", ("HP", "Ethernet") },
        { "C8:B5:AD", ("HP", "Ethernet") },
        { "C8:CB:B8", ("HP", "Ethernet") },
        { "D0:7E:28", ("HP", "Ethernet") },
        { "D4:85:64", ("HP", "Ethernet") },
        { "D4:C9:EF", ("HP", "Ethernet") },
        { "D8:9D:67", ("HP", "Ethernet") },
        { "D8:D3:85", ("HP", "Ethernet") },
        { "DC:4A:3E", ("HP", "Ethernet") },
        { "E4:11:5B", ("HP", "Ethernet") },
        { "E8:39:35", ("HP", "Ethernet") },
        { "EC:B1:D7", ("HP", "Ethernet") },
        { "F0:92:1C", ("HP", "Ethernet") },
        { "F4:03:43", ("HP", "Ethernet") },
        { "F4:CE:46", ("HP", "Ethernet") },
        { "FC:15:B4", ("HP", "Ethernet") },

        // Lenovo
        { "00:06:1B", ("Lenovo", "Ethernet") },
        { "00:09:2D", ("Lenovo", "Ethernet") },
        { "00:0A:E4", ("Lenovo", "Ethernet") },
        { "00:11:25", ("Lenovo", "Ethernet") },
        { "00:12:FE", ("Lenovo", "Ethernet") },
        { "00:16:41", ("Lenovo", "Ethernet") },
        { "00:1A:6B", ("Lenovo", "Ethernet") },
        { "00:1E:37", ("Lenovo", "Ethernet") },
        { "08:2E:5F", ("Lenovo", "Ethernet") },
        { "10:A5:1D", ("Lenovo", "Ethernet") },
        { "18:42:2F", ("Lenovo", "Ethernet") },
        { "28:D2:44", ("Lenovo", "Ethernet") },
        { "2C:76:8A", ("Lenovo", "Ethernet") },
        { "30:E1:71", ("Lenovo", "Ethernet") },
        { "4C:CC:6A", ("Lenovo", "Ethernet") },
        { "50:7B:9D", ("Lenovo", "Ethernet") },
        { "60:57:18", ("Lenovo", "Ethernet") },
        { "70:72:CF", ("Lenovo", "Ethernet") },
        { "74:E5:0B", ("Lenovo", "Ethernet") },
        { "7C:21:4A", ("Lenovo", "Ethernet") },
        { "84:7A:88", ("Lenovo", "Ethernet") },
        { "8C:16:45", ("Lenovo", "Ethernet") },
        { "98:FA:9B", ("Lenovo", "Ethernet") },
        { "A4:5E:60", ("Lenovo", "Ethernet") },
        { "B0:8B:CF", ("Lenovo", "Ethernet") },
        { "B4:69:21", ("Lenovo", "Ethernet") },
        { "C8:1F:66", ("Lenovo", "Ethernet") },
        { "E8:4E:06", ("Lenovo", "Ethernet") },
        { "F0:4D:A2", ("Lenovo", "Ethernet") },
        { "F4:8C:50", ("Lenovo", "Ethernet") },
        { "FC:44:82", ("Lenovo", "Ethernet") },

        // Amazon/Ring/Echo
        { "00:BB:3A", ("Amazon", "WiFi") },
        { "0C:47:C9", ("Amazon", "WiFi") },
        { "10:CE:A9", ("Amazon", "WiFi") },
        { "18:74:2E", ("Amazon", "WiFi") },
        { "28:78:0E", ("Amazon", "WiFi") },
        { "34:D2:70", ("Amazon", "WiFi") },
        { "38:F7:3D", ("Amazon", "WiFi") },
        { "40:B4:CD", ("Amazon", "WiFi") },
        { "44:65:0D", ("Amazon", "WiFi") },
        { "50:DC:E7", ("Amazon", "WiFi") },
        { "50:F5:DA", ("Amazon", "WiFi") },
        { "58:5D:CB", ("Amazon", "WiFi") },
        { "68:37:E9", ("Amazon", "WiFi") },
        { "68:54:FD", ("Amazon", "WiFi") },
        { "6C:56:97", ("Amazon", "WiFi") },
        { "74:75:48", ("Amazon", "WiFi") },
        { "74:C2:46", ("Amazon", "WiFi") },
        { "78:E1:03", ("Amazon", "WiFi") },
        { "84:D6:D0", ("Amazon", "WiFi") },
        { "88:71:B1", ("Amazon", "WiFi") },
        { "8C:C8:CD", ("Amazon", "WiFi") },
        { "A0:02:DC", ("Amazon", "WiFi") },
        { "AC:63:BE", ("Amazon", "WiFi") },
        { "B4:7C:9C", ("Amazon", "WiFi") },
        { "B8:AE:6E", ("Amazon/Ring", "WiFi") },
        { "C8:E2:65", ("Amazon/Ring", "WiFi") },
        { "CC:F7:35", ("Amazon", "WiFi") },
        { "D0:03:4B", ("Amazon/Ring", "WiFi") },
        { "DC:54:75", ("Amazon", "WiFi") },
        { "F0:27:2D", ("Amazon", "WiFi") },
        { "FC:65:DE", ("Amazon", "WiFi") },

        // Raspberry Pi
        { "B8:27:EB", ("Raspberry Pi", "Ethernet") },
        { "DC:A6:32", ("Raspberry Pi", "Ethernet") },
        { "E4:5F:01", ("Raspberry Pi", "Ethernet") },

        // Realtek (common chip manufacturer)
        { "00:E0:4C", ("Realtek", "Ethernet") },
        { "52:54:00", ("Realtek/QEMU", "Virtual") },

        // VMware
        { "00:0C:29", ("VMware", "Virtual") },
        { "00:50:56", ("VMware", "Virtual") },

        // VirtualBox
        { "08:00:27", ("VirtualBox", "Virtual") },

        // Broadcom
        { "00:10:18", ("Broadcom", "Ethernet") },
        { "00:14:A5", ("Broadcom", "WiFi") },
        { "00:16:B6", ("Broadcom", "Ethernet") },
        { "00:26:86", ("Broadcom", "Ethernet") },

        // Xiaomi
        { "00:9E:C8", ("Xiaomi", "WiFi") },
        { "04:CF:8C", ("Xiaomi", "WiFi") },
        { "0C:1D:AF", ("Xiaomi", "WiFi") },
        { "10:2A:B3", ("Xiaomi", "WiFi") },
        { "14:F6:5A", ("Xiaomi", "WiFi") },
        { "18:59:36", ("Xiaomi", "WiFi") },
        { "20:82:C0", ("Xiaomi", "WiFi") },
        { "28:6C:07", ("Xiaomi", "WiFi") },
        { "2C:8A:72", ("Xiaomi", "WiFi") },
        { "34:80:B3", ("Xiaomi", "WiFi") },
        { "38:A4:ED", ("Xiaomi", "WiFi") },
        { "50:64:2B", ("Xiaomi", "WiFi") },
        { "58:44:98", ("Xiaomi", "WiFi") },
        { "64:09:80", ("Xiaomi", "WiFi") },
        { "68:28:BA", ("Xiaomi", "WiFi") },
        { "74:51:BA", ("Xiaomi", "WiFi") },
        { "7C:1D:D9", ("Xiaomi", "WiFi") },
        { "8C:BE:BE", ("Xiaomi", "WiFi") },
        { "98:FA:E3", ("Xiaomi", "WiFi") },
        { "AC:F7:F3", ("Xiaomi", "WiFi") },
        { "B0:E2:35", ("Xiaomi", "WiFi") },
        { "C4:6A:B7", ("Xiaomi", "WiFi") },
        { "D4:97:0B", ("Xiaomi", "WiFi") },
        { "E8:AB:F3", ("Xiaomi", "WiFi") },
        { "F0:B4:29", ("Xiaomi", "WiFi") },
        { "F8:A4:5F", ("Xiaomi", "WiFi") },

        // Huawei
        { "00:18:82", ("Huawei", "WiFi") },
        { "00:1E:10", ("Huawei", "WiFi") },
        { "00:22:A1", ("Huawei", "WiFi") },
        { "00:25:68", ("Huawei", "WiFi") },
        { "00:25:9E", ("Huawei", "WiFi") },
        { "00:46:4B", ("Huawei", "WiFi") },
        { "00:66:4B", ("Huawei", "WiFi") },
        { "00:E0:FC", ("Huawei", "WiFi") },
        { "04:02:1F", ("Huawei", "WiFi") },
        { "04:25:C5", ("Huawei", "WiFi") },
        { "04:33:89", ("Huawei", "WiFi") },
        { "04:4F:4C", ("Huawei", "WiFi") },
        { "04:B0:E7", ("Huawei", "WiFi") },
        { "04:F9:38", ("Huawei", "WiFi") },
        { "08:19:A6", ("Huawei", "WiFi") },
        { "08:63:61", ("Huawei", "WiFi") },
        { "08:7A:4C", ("Huawei", "WiFi") },
        { "0C:37:DC", ("Huawei", "WiFi") },
        { "10:47:80", ("Huawei", "WiFi") },
        { "10:C6:1F", ("Huawei", "WiFi") },
        { "14:30:04", ("Huawei", "WiFi") },
        { "14:A0:F8", ("Huawei", "WiFi") },
        { "18:D2:76", ("Huawei", "WiFi") },
        { "1C:1D:67", ("Huawei", "WiFi") },
        { "20:08:ED", ("Huawei", "WiFi") },
        { "20:0B:C7", ("Huawei", "WiFi") },
        { "20:2B:C1", ("Huawei", "WiFi") },
        { "24:09:95", ("Huawei", "WiFi") },
        { "24:69:A5", ("Huawei", "WiFi") },
        { "24:DF:6A", ("Huawei", "WiFi") },
        { "28:31:52", ("Huawei", "WiFi") },
        { "28:5F:DB", ("Huawei", "WiFi") },
        { "28:6E:D4", ("Huawei", "WiFi") },
        { "2C:9D:1E", ("Huawei", "WiFi") },
        { "30:D1:7E", ("Huawei", "WiFi") },
        { "34:00:A3", ("Huawei", "WiFi") },
        { "34:12:98", ("Huawei", "WiFi") },
        { "34:6B:D3", ("Huawei", "WiFi") },
        { "38:37:8B", ("Huawei", "WiFi") },
        { "38:BC:01", ("Huawei", "WiFi") },
        { "3C:47:11", ("Huawei", "WiFi") },
        { "3C:DF:BD", ("Huawei", "WiFi") },
        { "40:4D:8E", ("Huawei", "WiFi") },
        { "44:55:B1", ("Huawei", "WiFi") },
        { "44:6A:2E", ("Huawei", "WiFi") },
        { "48:00:31", ("Huawei", "WiFi") },
        { "48:46:FB", ("Huawei", "WiFi") },
        { "48:62:76", ("Huawei", "WiFi") },
        { "4C:1F:CC", ("Huawei", "WiFi") },
        { "4C:54:99", ("Huawei", "WiFi") },
        { "4C:8B:EF", ("Huawei", "WiFi") },
        { "50:01:6B", ("Huawei", "WiFi") },
        { "54:89:98", ("Huawei", "WiFi") },
        { "54:A5:1B", ("Huawei", "WiFi") },
        { "58:2A:F7", ("Huawei", "WiFi") },
        { "58:60:5F", ("Huawei", "WiFi") },
        { "5C:09:79", ("Huawei", "WiFi") },
        { "5C:7D:5E", ("Huawei", "WiFi") },
        { "60:DE:44", ("Huawei", "WiFi") },
        { "64:3E:8C", ("Huawei", "WiFi") },
        { "68:A0:F6", ("Huawei", "WiFi") },
        { "6C:B7:49", ("Huawei", "WiFi") },
        { "70:19:2F", ("Huawei", "WiFi") },
        { "70:54:F5", ("Huawei", "WiFi") },
        { "70:72:3C", ("Huawei", "WiFi") },
        { "70:7B:E8", ("Huawei", "WiFi") },
        { "74:88:2A", ("Huawei", "WiFi") },
        { "78:D7:52", ("Huawei", "WiFi") },
        { "78:F5:57", ("Huawei", "WiFi") },
        { "7C:60:97", ("Huawei", "WiFi") },
        { "7C:A2:3E", ("Huawei", "WiFi") },
        { "80:B6:86", ("Huawei", "WiFi") },
        { "80:D0:9B", ("Huawei", "WiFi") },
        { "80:FB:06", ("Huawei", "WiFi") },
        { "84:5B:12", ("Huawei", "WiFi") },
        { "84:A8:E4", ("Huawei", "WiFi") },
        { "88:28:B3", ("Huawei", "WiFi") },
        { "88:53:D4", ("Huawei", "WiFi") },
        { "88:CF:98", ("Huawei", "WiFi") },
        { "88:E3:AB", ("Huawei", "WiFi") },
        { "8C:34:FD", ("Huawei", "WiFi") },
        { "90:17:AC", ("Huawei", "WiFi") },
        { "90:4E:2B", ("Huawei", "WiFi") },
        { "90:67:1C", ("Huawei", "WiFi") },
        { "90:94:97", ("Huawei", "WiFi") },
        { "94:04:9C", ("Huawei", "WiFi") },
        { "94:77:2B", ("Huawei", "WiFi") },
        { "94:DB:C9", ("Huawei", "WiFi") },
        { "98:E7:F5", ("Huawei", "WiFi") },
        { "9C:28:EF", ("Huawei", "WiFi") },
        { "9C:52:F8", ("Huawei", "WiFi") },
        { "9C:71:3A", ("Huawei", "WiFi") },
        { "9C:B2:B2", ("Huawei", "WiFi") },
        { "A0:08:6F", ("Huawei", "WiFi") },
        { "A0:57:E3", ("Huawei", "WiFi") },
        { "A4:99:47", ("Huawei", "WiFi") },
        { "A4:BE:2B", ("Huawei", "WiFi") },
        { "A8:0C:63", ("Huawei", "WiFi") },
        { "A8:C8:3A", ("Huawei", "WiFi") },
        { "AC:4E:91", ("Huawei", "WiFi") },
        { "AC:61:75", ("Huawei", "WiFi") },
        { "AC:CF:85", ("Huawei", "WiFi") },
        { "AC:E2:15", ("Huawei", "WiFi") },
        { "AC:E8:7B", ("Huawei", "WiFi") },
        { "B0:5B:67", ("Huawei", "WiFi") },
        { "B4:15:13", ("Huawei", "WiFi") },
        { "B4:30:52", ("Huawei", "WiFi") },
        { "B8:08:D7", ("Huawei", "WiFi") },
        { "B8:BC:1B", ("Huawei", "WiFi") },
        { "BC:25:E0", ("Huawei", "WiFi") },
        { "BC:3F:8F", ("Huawei", "WiFi") },
        { "BC:62:0E", ("Huawei", "WiFi") },
        { "BC:76:70", ("Huawei", "WiFi") },
        { "C0:70:09", ("Huawei", "WiFi") },
        { "C4:05:28", ("Huawei", "WiFi") },
        { "C4:07:2F", ("Huawei", "WiFi") },
        { "C4:47:3F", ("Huawei", "WiFi") },
        { "C4:86:E9", ("Huawei", "WiFi") },
        { "C8:14:79", ("Huawei", "WiFi") },
        { "C8:51:95", ("Huawei", "WiFi") },
        { "CC:A2:23", ("Huawei", "WiFi") },
        { "CC:CC:81", ("Huawei", "WiFi") },
        { "D0:2D:B3", ("Huawei", "WiFi") },
        { "D0:3E:5C", ("Huawei", "WiFi") },
        { "D4:40:F0", ("Huawei", "WiFi") },
        { "D4:61:2E", ("Huawei", "WiFi") },
        { "D4:6A:A8", ("Huawei", "WiFi") },
        { "D4:6E:5C", ("Huawei", "WiFi") },
        { "D4:A1:48", ("Huawei", "WiFi") },
        { "D4:B1:10", ("Huawei", "WiFi") },
        { "D8:49:0B", ("Huawei", "WiFi") },
        { "DC:09:4C", ("Huawei", "WiFi") },
        { "DC:D2:FC", ("Huawei", "WiFi") },
        { "E0:19:1D", ("Huawei", "WiFi") },
        { "E0:24:7F", ("Huawei", "WiFi") },
        { "E0:28:6D", ("Huawei", "WiFi") },
        { "E0:97:96", ("Huawei", "WiFi") },
        { "E4:35:C8", ("Huawei", "WiFi") },
        { "E4:68:A3", ("Huawei", "WiFi") },
        { "E4:77:23", ("Huawei", "WiFi") },
        { "E4:7E:66", ("Huawei", "WiFi") },
        { "E8:08:8B", ("Huawei", "WiFi") },
        { "E8:68:19", ("Huawei", "WiFi") },
        { "E8:CD:2D", ("Huawei", "WiFi") },
        { "EC:23:3D", ("Huawei", "WiFi") },
        { "EC:38:8F", ("Huawei", "WiFi") },
        { "EC:CB:30", ("Huawei", "WiFi") },
        { "F0:2F:A7", ("Huawei", "WiFi") },
        { "F0:43:47", ("Huawei", "WiFi") },
        { "F4:55:9C", ("Huawei", "WiFi") },
        { "F4:C7:14", ("Huawei", "WiFi") },
        { "F4:DC:F9", ("Huawei", "WiFi") },
        { "F4:E3:FB", ("Huawei", "WiFi") },
        { "F8:01:13", ("Huawei", "WiFi") },
        { "F8:3D:FF", ("Huawei", "WiFi") },
        { "F8:4A:BF", ("Huawei", "WiFi") },
        { "F8:75:88", ("Huawei", "WiFi") },
        { "F8:E8:11", ("Huawei", "WiFi") },
        { "FC:48:EF", ("Huawei", "WiFi") },
        { "FC:E3:3C", ("Huawei", "WiFi") },

        // Sony
        { "00:01:4A", ("Sony", "Ethernet") },
        { "00:04:1F", ("Sony", "Ethernet") },
        { "00:12:EE", ("Sony", "Ethernet") },
        { "00:13:A9", ("Sony", "Ethernet") },
        { "00:15:C1", ("Sony", "Ethernet") },
        { "00:18:13", ("Sony", "Ethernet") },
        { "00:19:63", ("Sony", "Ethernet") },
        { "00:1A:80", ("Sony", "Ethernet") },
        { "00:1C:A4", ("Sony", "Ethernet") },
        { "00:1D:28", ("Sony", "Ethernet") },
        { "00:1D:BA", ("Sony", "Ethernet") },
        { "00:1E:A4", ("Sony", "Ethernet") },
        { "00:1F:E1", ("Sony", "Ethernet") },
        { "00:1F:E2", ("Sony", "Ethernet") },
        { "00:21:4C", ("Sony", "Ethernet") },
        { "00:21:4F", ("Sony", "Ethernet") },
        { "00:22:98", ("Sony", "Ethernet") },
        { "00:24:BE", ("Sony", "Ethernet") },
        { "00:24:EF", ("Sony", "Ethernet") },
        { "00:25:D8", ("Sony", "Ethernet") },
        { "00:26:43", ("Sony", "Ethernet") },
        { "04:5D:4B", ("Sony", "WiFi") },
        { "10:4F:A8", ("Sony", "WiFi") },
        { "28:0D:FC", ("Sony", "WiFi") },
        { "30:17:C8", ("Sony", "WiFi") },
        { "30:F9:ED", ("Sony", "WiFi") },
        { "40:B8:37", ("Sony", "WiFi") },
        { "58:48:22", ("Sony", "WiFi") },
        { "70:9E:29", ("Sony", "WiFi") },
        { "78:C8:81", ("Sony", "WiFi") },
        { "94:CE:2C", ("Sony", "WiFi") },
        { "A0:E4:53", ("Sony", "WiFi") },
        { "AC:9B:0A", ("Sony", "WiFi") },
        { "B8:F9:34", ("Sony", "WiFi") },
        { "BC:60:A7", ("Sony/PlayStation", "WiFi") },
        { "F8:46:1C", ("Sony/PlayStation", "WiFi") },
        { "FC:0F:E6", ("Sony", "WiFi") },

        // LG
        { "00:05:C9", ("LG", "Ethernet") },
        { "00:1C:62", ("LG", "Ethernet") },
        { "00:1E:75", ("LG", "Ethernet") },
        { "00:1F:6B", ("LG", "Ethernet") },
        { "00:1F:E3", ("LG", "Ethernet") },
        { "00:22:A9", ("LG", "Ethernet") },
        { "00:26:E2", ("LG", "Ethernet") },
        { "08:D4:6A", ("LG", "WiFi") },
        { "10:68:3F", ("LG", "WiFi") },
        { "10:F9:6F", ("LG", "WiFi") },
        { "14:C9:13", ("LG", "WiFi") },
        { "1C:5A:6B", ("LG", "WiFi") },
        { "20:21:A5", ("LG", "WiFi") },
        { "28:A0:2B", ("LG", "WiFi") },
        { "2C:54:CF", ("LG", "WiFi") },
        { "34:4D:F7", ("LG", "WiFi") },
        { "34:FC:EF", ("LG", "WiFi") },
        { "38:8C:50", ("LG", "WiFi") },
        { "3C:BD:D8", ("LG", "WiFi") },
        { "40:B0:FA", ("LG", "WiFi") },
        { "48:59:29", ("LG", "WiFi") },
        { "4C:BC:A5", ("LG", "WiFi") },
        { "58:3F:54", ("LG", "WiFi") },
        { "5C:A3:9D", ("LG", "WiFi") },
        { "64:99:5D", ("LG", "WiFi") },
        { "6C:D6:8A", ("LG", "WiFi") },
        { "78:5D:C8", ("LG", "WiFi") },
        { "7C:1C:4E", ("LG", "WiFi") },
        { "88:C9:D0", ("LG", "WiFi") },
        { "8C:3A:E3", ("LG", "WiFi") },
        { "A0:39:EE", ("LG", "WiFi") },
        { "A8:16:D0", ("LG", "WiFi") },
        { "A8:23:FE", ("LG", "WiFi") },
        { "AC:0D:1B", ("LG", "WiFi") },
        { "B4:E6:2A", ("LG", "WiFi") },
        { "BC:F5:AC", ("LG", "WiFi") },
        { "C4:36:6C", ("LG", "WiFi") },
        { "C4:9A:02", ("LG", "WiFi") },
        { "CC:2D:8C", ("LG", "WiFi") },
        { "D0:13:FD", ("LG", "WiFi") },
        { "E8:5B:5B", ("LG", "WiFi") },
        { "F8:0C:F3", ("LG", "WiFi") },
        { "F8:95:C7", ("LG", "WiFi") },
        { "FC:F1:36", ("LG", "WiFi") },

        // Nintendo
        { "00:09:BF", ("Nintendo", "WiFi") },
        { "00:16:56", ("Nintendo", "WiFi") },
        { "00:17:AB", ("Nintendo", "WiFi") },
        { "00:19:1D", ("Nintendo", "WiFi") },
        { "00:19:FD", ("Nintendo", "WiFi") },
        { "00:1A:E9", ("Nintendo", "WiFi") },
        { "00:1B:EA", ("Nintendo", "WiFi") },
        { "00:1B:EA", ("Nintendo", "WiFi") },
        { "00:1C:BE", ("Nintendo", "WiFi") },
        { "00:1D:BC", ("Nintendo", "WiFi") },
        { "00:1E:35", ("Nintendo", "WiFi") },
        { "00:1E:A9", ("Nintendo", "WiFi") },
        { "00:1F:32", ("Nintendo", "WiFi") },
        { "00:1F:C5", ("Nintendo", "WiFi") },
        { "00:21:47", ("Nintendo", "WiFi") },
        { "00:21:BD", ("Nintendo", "WiFi") },
        { "00:22:4C", ("Nintendo", "WiFi") },
        { "00:22:AA", ("Nintendo", "WiFi") },
        { "00:23:31", ("Nintendo", "WiFi") },
        { "00:23:CC", ("Nintendo", "WiFi") },
        { "00:24:1E", ("Nintendo", "WiFi") },
        { "00:24:44", ("Nintendo", "WiFi") },
        { "00:24:F3", ("Nintendo", "WiFi") },
        { "00:25:A0", ("Nintendo", "WiFi") },
        { "00:26:59", ("Nintendo", "WiFi") },
        { "00:27:09", ("Nintendo", "WiFi") },
        { "2C:10:C1", ("Nintendo", "WiFi") },
        { "34:AF:2C", ("Nintendo", "WiFi") },
        { "40:D2:8A", ("Nintendo", "WiFi") },
        { "58:BD:A3", ("Nintendo", "WiFi") },
        { "5C:52:1E", ("Nintendo", "WiFi") },
        { "64:B5:C6", ("Nintendo", "WiFi") },
        { "78:A2:A0", ("Nintendo", "WiFi") },
        { "7C:BB:8A", ("Nintendo", "WiFi") },
        { "8C:56:C5", ("Nintendo", "WiFi") },
        { "98:41:5C", ("Nintendo", "WiFi") },
        { "98:B6:E9", ("Nintendo", "WiFi") },
        { "A4:5C:27", ("Nintendo", "WiFi") },
        { "A4:C0:E1", ("Nintendo", "WiFi") },
        { "B8:8A:EC", ("Nintendo", "WiFi") },
        { "CC:9E:00", ("Nintendo", "WiFi") },
        { "D8:6B:F7", ("Nintendo", "WiFi") },
        { "E0:0C:7F", ("Nintendo", "WiFi") },
        { "E0:E7:51", ("Nintendo", "WiFi") },
        { "E8:4E:CE", ("Nintendo", "WiFi") },
        { "EC:0E:C4", ("Nintendo", "WiFi") },

        // Roku
        { "00:0D:4B", ("Roku", "WiFi") },
        { "08:05:81", ("Roku", "WiFi") },
        { "10:59:32", ("Roku", "WiFi") },
        { "20:EF:BD", ("Roku", "WiFi") },
        { "2C:A1:7D", ("Roku", "WiFi") },
        { "48:E7:29", ("Roku", "WiFi") },
        { "88:DE:A9", ("Roku", "WiFi") },
        { "AC:3A:7A", ("Roku", "WiFi") },
        { "B0:A7:37", ("Roku", "WiFi") },
        { "B0:EE:7B", ("Roku", "WiFi") },
        { "C8:3A:6B", ("Roku", "WiFi") },
        { "D0:4D:C6", ("Roku", "WiFi") },
        { "D8:31:34", ("Roku", "WiFi") },

        // Wyze
        { "2C:AA:8E", ("Wyze", "WiFi") },

        // TP-Link Kasa / Smart Home
        { "50:C7:BF", ("TP-Link/Kasa", "WiFi") },
        { "60:32:B1", ("TP-Link/Kasa", "WiFi") },
        { "B0:BE:76", ("TP-Link/Kasa", "WiFi") },
        
        // Ubiquiti
        { "00:15:6D", ("Ubiquiti", "WiFi") },
        { "00:27:22", ("Ubiquiti", "WiFi") },
        { "04:18:D6", ("Ubiquiti", "WiFi") },
        { "18:E8:29", ("Ubiquiti", "WiFi") },
        { "24:5A:4C", ("Ubiquiti", "WiFi") },
        { "44:D9:E7", ("Ubiquiti", "WiFi") },
        { "68:72:51", ("Ubiquiti", "WiFi") },
        { "74:83:C2", ("Ubiquiti", "WiFi") },
        { "78:8A:20", ("Ubiquiti", "WiFi") },
        { "80:2A:A8", ("Ubiquiti", "WiFi") },
        { "B4:FB:E4", ("Ubiquiti", "WiFi") },
        { "DC:9F:DB", ("Ubiquiti", "WiFi") },
        { "E0:63:DA", ("Ubiquiti", "WiFi") },
        { "F0:9F:C2", ("Ubiquiti", "WiFi") },
        { "FC:EC:DA", ("Ubiquiti", "WiFi") },

        // Espressif (ESP8266/ESP32 - common for IoT)
        { "18:FE:34", ("Espressif/ESP", "WiFi") },
        { "24:0A:C4", ("Espressif/ESP", "WiFi") },
        { "24:62:AB", ("Espressif/ESP", "WiFi") },
        { "24:6F:28", ("Espressif/ESP", "WiFi") },
        { "24:B2:DE", ("Espressif/ESP", "WiFi") },
        { "2C:3A:E8", ("Espressif/ESP", "WiFi") },
        { "30:AE:A4", ("Espressif/ESP", "WiFi") },
        { "3C:61:05", ("Espressif/ESP", "WiFi") },
        { "3C:71:BF", ("Espressif/ESP", "WiFi") },
        { "40:F5:20", ("Espressif/ESP", "WiFi") },
        { "48:3F:DA", ("Espressif/ESP", "WiFi") },
        { "4C:11:AE", ("Espressif/ESP", "WiFi") },
        { "54:5A:A6", ("Espressif/ESP", "WiFi") },
        { "5C:CF:7F", ("Espressif/ESP", "WiFi") },
        { "60:01:94", ("Espressif/ESP", "WiFi") },
        { "68:C6:3A", ("Espressif/ESP", "WiFi") },
        { "84:0D:8E", ("Espressif/ESP", "WiFi") },
        { "84:CC:A8", ("Espressif/ESP", "WiFi") },
        { "84:F3:EB", ("Espressif/ESP", "WiFi") },
        { "8C:AA:B5", ("Espressif/ESP", "WiFi") },
        { "90:97:D5", ("Espressif/ESP", "WiFi") },
        { "94:B9:7E", ("Espressif/ESP", "WiFi") },
        { "98:CD:AC", ("Espressif/ESP", "WiFi") },
        { "98:F4:AB", ("Espressif/ESP", "WiFi") },
        { "A0:20:A6", ("Espressif/ESP", "WiFi") },
        { "A4:7B:9D", ("Espressif/ESP", "WiFi") },
        { "A4:CF:12", ("Espressif/ESP", "WiFi") },
        { "AC:0B:FB", ("Espressif/ESP", "WiFi") },
        { "AC:D0:74", ("Espressif/ESP", "WiFi") },
        { "B4:E6:2D", ("Espressif/ESP", "WiFi") },
        { "BC:DD:C2", ("Espressif/ESP", "WiFi") },
        { "C4:4F:33", ("Espressif/ESP", "WiFi") },
        { "C8:2B:96", ("Espressif/ESP", "WiFi") },
        { "CC:50:E3", ("Espressif/ESP", "WiFi") },
        { "D8:A0:1D", ("Espressif/ESP", "WiFi") },
        { "D8:BF:C0", ("Espressif/ESP", "WiFi") },
        { "DC:4F:22", ("Espressif/ESP", "WiFi") },
        { "E8:DB:84", ("Espressif/ESP", "WiFi") },
        { "EC:FA:BC", ("Espressif/ESP", "WiFi") },
        { "F0:08:D1", ("Espressif/ESP", "WiFi") },
        { "FC:F5:C4", ("Espressif/ESP", "WiFi") },
    };

    /// <summary>
    /// Gets the manufacturer name for a given MAC address
    /// </summary>
    public string GetManufacturer(string macAddress)
    {
        if (string.IsNullOrWhiteSpace(macAddress) || macAddress == "Unknown")
            return "Unknown";

        var oui = NormalizeAndExtractOui(macAddress);
        if (oui != null && OuiDatabase.TryGetValue(oui, out var info))
        {
            return info.Manufacturer;
        }

        return "Unknown";
    }

    /// <summary>
    /// Gets the adapter type (WiFi, Ethernet, Virtual) for a given MAC address
    /// </summary>
    public string GetAdapterType(string macAddress)
    {
        if (string.IsNullOrWhiteSpace(macAddress) || macAddress == "Unknown")
            return "Unknown";

        var oui = NormalizeAndExtractOui(macAddress);
        if (oui != null && OuiDatabase.TryGetValue(oui, out var info))
        {
            return info.Type;
        }

        return "Unknown";
    }

    /// <summary>
    /// Normalizes a MAC address and extracts the OUI (first 3 bytes)
    /// </summary>
    private static string? NormalizeAndExtractOui(string macAddress)
    {
        // Remove common separators and convert to uppercase
        var cleaned = macAddress.Replace(":", "").Replace("-", "").Replace(".", "").ToUpperInvariant();

        if (cleaned.Length < 6)
            return null;

        // Extract first 6 characters (3 bytes) and format as XX:XX:XX
        var oui = $"{cleaned[0..2]}:{cleaned[2..4]}:{cleaned[4..6]}";
        return oui;
    }
}
